### ISSUE TITLE
Crash on 1.6.0 with Luma 8 + Boot9Strap

### ISSUE THREAD

**Issue by deathspawn** [Kaisogen/CookieCollector-3DS-#5]
I keep getting a crash upon starting the app. Doesn't matter if I use the 3dsx file or the cia. Also happens on 1.5.1.

I'm using the latest boot9strap + luma on a 11.4 n3DS.

![Top Screen](https://i.imgur.com/WixIBYl.jpg)
![Bottom Screen](https://i.imgur.com/X898TZ1.jpg)

Edit: Sorry for the 2 images, it was hard to get my camera to focus.

Dump from luma:

`DE C0 AD DE  FE CA AD DE  02 00 01 00  0B 00 00 00
03 00 00 00  FC 01 00 00  5C 00 00 00  30 00 00 00
38 01 00 00  10 00 00 00  F8 B4 12 00  F0 DF 12 00
08 00 00 00  01 00 00 00  00 00 00 00  F0 DF 12 00
F8 B4 12 00  08 00 00 00  F8 24 01 00  00 00 00 00
10 27 00 00  00 00 00 00  20 14 01 08  C8 7E 00 08
50 9F 10 00  88 9C 10 00  10 00 07 20  05 00 00 00
07 00 00 00  70 00 00 00  00 00 00 00  40 0A B8 EE
40 0A B8 EE  38 40 9D E5  4B 00 00 0A  00 00 50 E3
00 60 A0 E1  01 50 A0 E1  08 30 8D E5  0C 20 8D E5
02 00 00 0A  38 30 90 E5  00 00 53 E3  98 00 00 0A
70 30 94 E5  D4 69 12 00  E8 54 12 00  01 00 00 00
08 00 00 00  40 12 01 08  F0 DF 12 00  08 00 00 00
01 00 00 00  00 00 00 00  F8 24 01 00  00 00 00 00
10 27 00 00  00 00 00 00  50 9F 10 00  00 00 00 00
02 06 00 00  8C 7F 00 08  00 00 00 00  00 00 00 00
88 13 00 00  00 00 00 00  C4 02 10 00  58 DF 12 00
DC 12 10 00  00 00 00 00  00 F0 12 00  00 00 43 00
88 13 00 00  00 00 00 00  F8 24 01 00  90 61 12 00
00 00 00 01  00 00 00 30  00 00 00 00  00 00 00 00
00 00 00 00  00 00 00 00  32 00 00 00  1E 00 00 00
00 00 00 00  00 00 00 00  32 00 00 00  1E 00 00 00
03 00 00 00  07 00 00 00  00 00 00 00  00 00 00 00
00 00 00 00  01 00 00 00  90 61 12 00  00 00 00 01
00 4E 0C 30  00 00 00 00  00 00 00 00  00 00 00 00
00 00 00 00  28 00 00 00  1E 00 00 00  00 00 00 00
00 00 00 00  28 00 00 00  1E 00 00 00  03 00 00 00
07 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00
01 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00
00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00
00 00 00 00  00 00 00 00  EC 04 10 00  68 6F 6D 65
62 72 65 77  00 FF F3 0F  00 00 04 00`

**Comment by deathspawn** [comment]
<insert Homer Simpson D'Oh>

I didn't have the data folder in the right spot. Need it in the 3ds folder, not the 3ds's sdcard root folder...

**Comment by GabrielRRussell** [comment]
Don't worry about this. I fixed this in later revisions by making sure the directories exist.
